### ISSUE TITLE
nebula theme doesn't work in the latest version of cosine

### ISSUE THREAD

**Issue by Khf20** [CosmoCreeper/Sine#182]
![Image](https://github.com/user-attachments/assets/be4f3793-2281-4d74-b645-6ca58fdf8b10)

![Image](https://github.com/user-attachments/assets/eb0eafa0-22ce-4a02-b4ed-0cbb193f53ea)

**Comment by Khf20** [comment]
![Image](https://github.com/user-attachments/assets/2af2521b-5c26-480e-bd16-7b887c33341f)

now my mod is not working

**Comment by Khf20** [comment]
i use zen twilight 

![Image](https://github.com/user-attachments/assets/8805d26a-36aa-4954-8367-222d40c534bb)

**Comment by CosmoCreeper** [comment]
@Khf20 Zen Twilight should be working now. It appears your mod has the incorrect preferences? Could you give me your mod repo so I can look it over? Also, try uninstalling and reinstalling Nebula.

**Comment by Khf20** [comment]
> [@Khf20](https://github.com/Khf20) Zen Twilight should be working now. It appears your mod has the incorrect preferences? Could you give me your mod repo so I can look it over? Also, try uninstalling and reinstalling Nebula.

The mods I'm using now are working after I tried reinstalling them but the nebula theme still doesn't work

**Comment by CosmoCreeper** [comment]
@Khf20 could you share the data that Nebula has in the sine-mods folder of your chrome dir in your profile?

**Comment by Khf20** [comment]
> [@Khf20](https://github.com/Khf20) could you share the data that Nebula has in the sine-mods folder of your chrome dir in your profile?

Wait, I just tried to uninstall and reinstall the nebula theme and suddenly my zen application was not responding and I tried to open the application over and over again but it didn't work and I tried to delete nebula in the profile folder and then it could be opened

**Comment by CosmoCreeper** [comment]
@Khf20 Ahhh, that's it. I noticed this issue before and I think I have a fix. I'll release v2.1.1 in a bit, but in the meantime, the fix is to go to your profile folder (accessible from your ```about:support``` page) and go to the chrome directory, then delete the zen-themes.css file. Then it should work properly.

**Comment by Khf20** [comment]
> [@Khf20](https://github.com/Khf20) Ahhh, that's it. I noticed this issue before and I think I have a fix. I'll release v2.1.1 in a bit, but in the meantime, the fix is to go to your profile folder (accessible from your `about:support` page) and go to the chrome directory, then delete the zen-themes.css file. Then it should work properly.

work 

![Image](https://github.com/user-attachments/assets/5d16b72c-f378-42ae-a061-2b749d6cb3f7)

**Comment by CosmoCreeper** [comment]
@Khf20 It's working?

**Comment by xXSalamanderXx** [comment]
My nebula broke on the latest update of sine aswell. Infact all my mods broke and toggling them off and on again fixed most of them, apart from nebula. Basically all the movement animations, such as the rotating gradients in nebula are just static. No more animations.

![Image](https://github.com/user-attachments/assets/859c7768-fac4-473c-8c7e-c76cb22f58c7) --> The gradient doesnt move, its stuck like that.

**Comment by xXSalamanderXx** [comment]
Also it installed as "cosine" even though I ran the normal sine installer. And I _don't have a zen-themes.css_ file so it's not that.

**Comment by CosmoCreeper** [comment]
@xXSalamanderXx Could you try removing and adding back Nebula? Also, that cosine thing was a flaw in my end (i accidentally pushed the cosine version to the installer, but its fixed with the v2.1 auto-installer, so sorry about that.) Also, you are on Twilight?

**Comment by xXSalamanderXx** [comment]
@CosmoCreeper No, I used the v2.1 installer. It's not fixed coz that's the one that keeps installing cosine. I've ran it twice now and get cosine. And no, I'm on beta zen.

**Comment by xXSalamanderXx** [comment]
@CosmoCreeper I removed nebula, and reinstalled nebula. And now all the mods are broken, (as if they are toggled off, but they are toggled on). I'm gonna go back to an older sine version, it's really broken.

**Comment by CosmoCreeper** [comment]
@xXSalamanderXx Oh no. Don't go to an older version, this one is stable. Use the Ctrl+Shift+J shortcut to get the logs. The Cosine thing is cause of a dropdown pref, but that's fine for now considering both are on the same version for right now.

**Comment by xXSalamanderXx** [comment]
@CosmoCreeper. Okay I've tried again with 2.1.1 - and still all mods are not working. This is really frustrating, as it was working before when I was on 1.x (cant remember exact version I was on before but it ran perfect). 

![Image](https://github.com/user-attachments/assets/a9e91e07-6c93-43c6-8c7e-ebdaa0f2abce)

**Comment by xXSalamanderXx** [comment]
It's somehow linked to minimal exit menu, as when I **disable minimal exit menu, the mods load**. However, I am **unable to get minimal exit menu working, AND the nebula animations don't work either.** 

This log is after toggling minimal exit menu on and off.

![Image](https://github.com/user-attachments/assets/a8f60d3a-394d-4a00-9254-3fe44a58d556)

**Comment by xXSalamanderXx** [comment]
@CosmoCreeper  Sorry for the spam. 

So I completely removed all of sine from my profile folder and zen application. I did a completely fresh install, with no zen mods or anything. And it still does not work. It's getting **favicon errors and gZenmods is undefined errors**. But when I did the same fresh install from an older version of sine, I don't have any errors at all!

This is from a completely fresh install of Sine 2.1.1, with a clean profile folder and no zen mods ⬇️

![Image](https://github.com/user-attachments/assets/bf9010a7-71e6-48ad-95f5-0f52b1ad45cb)

**Comment by CosmoCreeper** [comment]
@xXSalamanderXx Okay, what errors are from Sine? None of these have to do with Sine (most are usual), so maybe its below those? Did you clear startup cache?

**Comment by xXSalamanderXx** [comment]
@CosmoCreeper yes I cleared startup cache. All I know is, the new version isn't working compared to the old. Look at the vid - nebula animations no longer work. Also look at the above screenshots before I did the complete reset.

https://github.com/user-attachments/assets/4f3165f3-0afd-4778-9cf9-273695e88823

**Comment by CosmoCreeper** [comment]
@xXSalamanderXx I mean, that seems like a Nebula issue. Is the rest of Sine working?

**Comment by xXSalamanderXx** [comment]
@CosmoCreeper Nebula is working **fine** when installed manually or on older sine version.. 
It's not Nebula's issue. It was all working yesterday until I tried updating Sine.

**Comment by xXSalamanderXx** [comment]
No problems, I'm unsure how to proceed from here. I may go back to manual installs as I've had too many issues with Sine. But good luck with the project.

**Comment by CosmoCreeper** [comment]
@xXSalamanderXx Yeah, I'm very sorry, no one else appears to have these issues. Trying a new profile would probably work however, if you are willing to try that.

**Comment by xXSalamanderXx** [comment]
That's okay, Sine works great on Windows so I'll keep using it on that OS. But with Linux is where I encounter all these issues. Not sure if you use Linux.. or you could run Linux in a VM and can try improve Linux compatibility in future e.g. for app images, flatpaks of Zen.

**Comment by CosmoCreeper** [comment]
@xXSalamanderXx Well, app images are supported, but you have to extract them. Flatpak can be added support for, but it should be important to note to users that Sine on flatpak requires removing the sandbox.

**Comment by xXSalamanderXx** [comment]
Yeah I've been using app image extractor and that was working fine to install. 

However the auto update doesn't work with app image right? Because you have to repackage it. 

So I was manually updating Sine and injecting it into the app image. Was just wondering if compatibility was an issue, but sounds like it 'should' work fine with my app image use case. Very odd.

**Comment by CosmoCreeper** [comment]
@xXSalamanderXx Does app image bundle the profiles or just the program? If it just bundles the program, then no, Sine will be able to auto-update.

**Comment by xXSalamanderXx** [comment]
Just the program 👍️

**Comment by CosmoCreeper** [comment]
@xXSalamanderXx Yeah, then it will auto-update.

**Comment by CosmoCreeper** [comment]
Okay, considering this issue is fixed, I'll close it.
