### ISSUE TITLE
Bug or idk

### ISSUE THREAD

**Issue by foteFungus** [CosmoCreeper/Sine#26]
So, i've installed Sine and all of my mods were gone, and i couldn't edit them, like they should be at the bottom but they were not

![Image](https://github.com/user-attachments/assets/df7ddb01-5ef6-4a66-8e81-7235bead492c)

then i reinstalled zen completely and installed Sine, and now i have another problem. When i press install on these mods (e.g. Transparent New tab or Advanced Tab Groups) they dissappear like they should, but when i reload the page the appear again like they are not installed.

**Comment by foteFungus** [comment]
![Image](https://github.com/user-attachments/assets/4946d5a4-f70d-4d9e-967a-1b30ffd299ac)
Now these 2 mods dissappeared and i checked the "chrome/zen-themes" folder, and they are installed
But i still don't have the mods at the bottom to configure them
(i tried to import them but the error occured)

**Comment by CosmoCreeper** [comment]
This appears to be a common problem and I will be testing out a patch on monday. Could you please let me know what mods you have so I can see if these specifically have any problems.

**Comment by foteFungus** [comment]
Okay, thanks, i'l be waiting on this for sure
Super URL Bar as i remember and Advanced Tab Groups, but i've downloaded it manually, and after that discovered Sine)

**Comment by CosmoCreeper** [comment]
> Okay, thanks, i'l be waiting on this for sure
> Super URL Bar as i remember and Advanced Tab Groups, but i've downloaded it manually, and after that discovered Sine)
> 

Yeses. That's it. You installed manually. Chances are that a missing property like the homepage is causing this. Wait, i know what it is! There is no safeguard for homepages in theme.json with missing properties. I know exactly what to do on monday so be looking towards v1.1.3.

**Comment by foteFungus** [comment]
I installed the mod manually, but not the Sine) or i misinterpreted your answer)

**Comment by CosmoCreeper** [comment]
My answer is that the github homepage is likely not set, leading to problems with our new theme.json compatibility features. I have never had mods without a homepage and that is likely why I never encountered this error.

**Comment by foteFungus** [comment]
Okay, good luck with fixing!

**Comment by CosmoCreeper** [comment]
> Okay, good luck with fixing!

@foteFungus, should be fixed now!

**Comment by BibekBhusal0** [comment]
I have updated to latest version but this is still not fixed.

**Comment by foteFungus** [comment]
Hi, @CosmoCreeper, thanks, I will check if mine is working today later

**Comment by foteFungus** [comment]
Hi again) @CosmoCreeper, everything is working fine for me!

**Comment by CosmoCreeper** [comment]
> I have updated to latest version but this is still not fixed.

You need to reset all your mods from the zen-themes.json and then try again.

**Comment by BibekBhusal0** [comment]
> You need to reset all your mods from the zen-themes.json and then try again.

Do you mean it from here?

![Image](https://github.com/user-attachments/assets/12e093dc-a32b-45e2-9972-94327fc1c21d)

![Image](https://github.com/user-attachments/assets/5215b908-2da6-4214-903c-53e66b213f04)

I have toggled it from here, it still don't work. I can't even see the options of Sine.

**Comment by CosmoCreeper** [comment]
Open up the ctrl+shift+j menu again and give me that data. Also, the zen-themes.json can be accessed by going to about:support, clicking open folder next to the profile folder section, and navigating to the zen-themes.json. you then have to replace it with ```{}```.

**Comment by BibekBhusal0** [comment]
> Open up the ctrl+shift+j menu again and give me that data. Also, the zen-themes.json can be accessed by going to about:support, clicking open folder next to the profile folder section, and navigating to the zen-themes.json. you then have to replace it with `{}`.

It works now, but all my mods are gone, do I have to reinstall them, or there is some other way to back it up. I have backup of zen-themes.json.

**Comment by CosmoCreeper** [comment]
I think you can reinstall or import.
