### ISSUE TITLE
Cannot see the Sine section in preferences

### ISSUE THREAD

**Issue by stantios** [CosmoCreeper/Sine#58]
Description: I've installed sine using the x64 installer for mac, cleared my startup cache, restarted zen and when I went over to preferences, I couldn't find the Sine section anywhere as shown in the README. This issue could be related to https://github.com/CosmoCreeper/Sine/issues/41 but I'm not sure.

**Comment by CosmoCreeper** [comment]
@stantios this is a very known issue. What mods do you have? Could you give me your zen-themes.json from the root of your profile directory?

**Comment by stantios** [comment]
This is my list of mods:

- Bleeding Corners Fix
- Cleaner Extension Menu
- Floating Status Bar
- Only Close On Hover
- Revitalized devtools
- SuperPins
- Zen Colored Picker

Here is my zen-themes.json:
```json
{"7d577b21-4685-4db2-bb17-d39d08eec199":{"id":"7d577b21-4685-4db2-bb17-d39d08eec199","name":"Bleeding Corners Fix","description":"Fixes the white outlines (or artifacts) on the rounded corners that can appear on some pages.","homepage":"https://github.com/rsiebertdev/zen-themes","style":"https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/7d577b21-4685-4db2-bb17-d39d08eec199/chrome.css","readme":"https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/7d577b21-4685-4db2-bb17-d39d08eec199/readme.md","image":"https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/7d577b21-4685-4db2-bb17-d39d08eec199/image.png","author":"rsiebertdev","version":"1.0.3","tags":[],"createdAt":"2025-02-17","updatedAt":"2025-05-16","enabled":true},"1e86cf37-a127-4f24-b919-d265b5ce29a0":{"id":"1e86cf37-a127-4f24-b919-d265b5ce29a0","name":"Cleaner Extensions","description":"Remove header and reduce width of the Unified Extension Menu in Zen","homepage":"","style":"https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/1e86cf37-a127-4f24-b919-d265b5ce29a0/chrome.css","readme":"https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/1e86cf37-a127-4f24-b919-d265b5ce29a0/readme.md","image":"https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/1e86cf37-a127-4f24-b919-d265b5ce29a0/image.png","author":"KiKaraage","version":"2.1.0","preferences":"https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/1e86cf37-a127-4f24-b919-d265b5ce29a0/preferences.json","tags":[],"createdAt":"2024-09-03","updatedAt":"2025-05-22","enabled":true},"906c6915-5677-48ff-9bfc-096a02a72379":{"id":"906c6915-5677-48ff-9bfc-096a02a72379","name":"Floating Status Bar","description":"Mod for Zen Browser that detaches the status bar from the bottom left corner of the browser window.","homepage":"https://github.com/AmirhBeigi/zen-floating-statusbar/","style":"https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/906c6915-5677-48ff-9bfc-096a02a72379/chrome.css","readme":"https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/906c6915-5677-48ff-9bfc-096a02a72379/readme.md","image":"https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/906c6915-5677-48ff-9bfc-096a02a72379/image.png","author":"AmirhBeigi","version":"1.0.0","tags":[],"createdAt":"2024-10-06","updatedAt":"2025-01-26","enabled":true},"4596d8f9-f0b7-4aeb-aa92-851222dc1888":{"id":"4596d8f9-f0b7-4aeb-aa92-851222dc1888","name":"Only Close On Hover","description":"Show tab's close button only on hover, even on the active tab.","homepage":"","style":"https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/4596d8f9-f0b7-4aeb-aa92-851222dc1888/chrome.css","readme":"https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/4596d8f9-f0b7-4aeb-aa92-851222dc1888/readme.md","image":"https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/4596d8f9-f0b7-4aeb-aa92-851222dc1888/image.png","author":"p-sw","version":"1.0.0","tags":[],"createdAt":"2024-10-12","updatedAt":"2025-01-26","enabled":true},"0d218357-d5be-48f1-bbc0-5e7cb2d2e11f":{"id":"0d218357-d5be-48f1-bbc0-5e7cb2d2e11f","name":"Revitalized devtools","description":"A calmer theme for Zen's DevTools with added transitions and compatible white/dark modes.","homepage":"https://github.com/ArjiAmin/firefox-devtools","style":"https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/0d218357-d5be-48f1-bbc0-5e7cb2d2e11f/chrome.css","readme":"https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/0d218357-d5be-48f1-bbc0-5e7cb2d2e11f/readme.md","image":"https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/0d218357-d5be-48f1-bbc0-5e7cb2d2e11f/image.png","author":"ArjiAmin","version":"1.0.0","tags":[],"createdAt":"2025-03-30","updatedAt":"2025-03-31","enabled":true},"ad97bb70-0066-4e42-9b5f-173a5e42c6fc":{"id":"ad97bb70-0066-4e42-9b5f-173a5e42c6fc","name":"SuperPins","description":"This Zen Mod enhances pinned tabs/Essentials, by making some UI/UX changes.","homepage":"https://github.com/CosmoCreeper/Zen-Themes/tree/main/SuperPins","style":"https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/ad97bb70-0066-4e42-9b5f-173a5e42c6fc/chrome.css","readme":"https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/ad97bb70-0066-4e42-9b5f-173a5e42c6fc/readme.md","image":"https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/ad97bb70-0066-4e42-9b5f-173a5e42c6fc/image.png","author":"CosmoCreeper","version":"1.5.3","preferences":"https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/ad97bb70-0066-4e42-9b5f-173a5e42c6fc/preferences.json","tags":["tabs"],"createdAt":"2024-08-28","updatedAt":"2025-05-20","enabled":true},"03a8e7ef-cf00-4f41-bf24-a90deeafc9db":{"id":"03a8e7ef-cf00-4f41-bf24-a90deeafc9db","name":"Zen Colored Picker","description":"Adds the rainbow color pad to the theme picker","homepage":"https://github.com/Nimit1705/zen-colored-picker","style":"https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/03a8e7ef-cf00-4f41-bf24-a90deeafc9db/chrome.css","readme":"https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/03a8e7ef-cf00-4f41-bf24-a90deeafc9db/readme.md","image":"https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/03a8e7ef-cf00-4f41-bf24-a90deeafc9db/image.png","author":"Nimit1705","version":"1.0.1","tags":[],"createdAt":"2025-02-23","updatedAt":"2025-02-23","preferences":"https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/03a8e7ef-cf00-4f41-bf24-a90deeafc9db/preferences.json","enabled":true}}
```

**Comment by Buckeyes23** [comment]
Cosmo, I had the same problem on a different computer this morning. Tried installing from auto installer and it failed, didnt install anyhting on the computer, ran it in administrator also.  only way was with Nodejs.  On my original computer, Sine disappeared this morning after it updated to your new version, again, had to install using Nodejs

**Comment by CosmoCreeper** [comment]
@Buckeyes23 I believe the issue is due to a homepage failure, could you provide me with the same data I have requested for the original poster?

@stantios Try this for your zen-themes.json:
```json
{
  "7d577b21-4685-4db2-bb17-d39d08eec199": {
    "id": "7d577b21-4685-4db2-bb17-d39d08eec199",
    "name": "Bleeding Corners Fix",
    "description": "Fixes the white outlines (or artifacts) on the rounded corners that can appear on some pages.",
    "homepage": "https://github.com/rsiebertdev/zen-themes",
    "style": "https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/7d577b21-4685-4db2-bb17-d39d08eec199/chrome.css",
    "readme": "https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/7d577b21-4685-4db2-bb17-d39d08eec199/readme.md",
    "image": "https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/7d577b21-4685-4db2-bb17-d39d08eec199/image.png",
    "author": "rsiebertdev",
    "version": "1.0.3",
    "tags": [],
    "createdAt": "2025-02-17",
    "updatedAt": "2025-05-16",
    "enabled": true
  },
  "906c6915-5677-48ff-9bfc-096a02a72379": {
    "id": "906c6915-5677-48ff-9bfc-096a02a72379",
    "name": "Floating Status Bar",
    "description": "Mod for Zen Browser that detaches the status bar from the bottom left corner of the browser window.",
    "homepage": "https://github.com/AmirhBeigi/zen-floating-statusbar/",
    "style": "https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/906c6915-5677-48ff-9bfc-096a02a72379/chrome.css",
    "readme": "https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/906c6915-5677-48ff-9bfc-096a02a72379/readme.md",
    "image": "https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/906c6915-5677-48ff-9bfc-096a02a72379/image.png",
    "author": "AmirhBeigi",
    "version": "1.0.0",
    "tags": [],
    "createdAt": "2024-10-06",
    "updatedAt": "2025-01-26",
    "enabled": true
  },
  "0d218357-d5be-48f1-bbc0-5e7cb2d2e11f": {
    "id": "0d218357-d5be-48f1-bbc0-5e7cb2d2e11f",
    "name": "Revitalized devtools",
    "description": "A calmer theme for Zen's DevTools with added transitions and compatible white/dark modes.",
    "homepage": "https://github.com/ArjiAmin/firefox-devtools",
    "style": "https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/0d218357-d5be-48f1-bbc0-5e7cb2d2e11f/chrome.css",
    "readme": "https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/0d218357-d5be-48f1-bbc0-5e7cb2d2e11f/readme.md",
    "image": "https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/0d218357-d5be-48f1-bbc0-5e7cb2d2e11f/image.png",
    "author": "ArjiAmin",
    "version": "1.0.0",
    "tags": [],
    "createdAt": "2025-03-30",
    "updatedAt": "2025-03-31",
    "enabled": true
  },
  "ad97bb70-0066-4e42-9b5f-173a5e42c6fc": {
    "id": "ad97bb70-0066-4e42-9b5f-173a5e42c6fc",
    "name": "SuperPins",
    "description": "This Zen Mod enhances pinned tabs/Essentials, by making some UI/UX changes.",
    "homepage": "https://github.com/CosmoCreeper/Zen-Themes/tree/main/SuperPins",
    "style": "https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/ad97bb70-0066-4e42-9b5f-173a5e42c6fc/chrome.css",
    "readme": "https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/ad97bb70-0066-4e42-9b5f-173a5e42c6fc/readme.md",
    "image": "https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/ad97bb70-0066-4e42-9b5f-173a5e42c6fc/image.png",
    "author": "CosmoCreeper",
    "version": "1.5.3",
    "preferences": "https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/ad97bb70-0066-4e42-9b5f-173a5e42c6fc/preferences.json",
    "tags": ["tabs"],
    "createdAt": "2024-08-28",
    "updatedAt": "2025-05-20",
    "enabled": true
  },
  "03a8e7ef-cf00-4f41-bf24-a90deeafc9db": {
    "id": "03a8e7ef-cf00-4f41-bf24-a90deeafc9db",
    "name": "Zen Colored Picker",
    "description": "Adds the rainbow color pad to the theme picker",
    "homepage": "https://github.com/Nimit1705/zen-colored-picker",
    "style": "https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/03a8e7ef-cf00-4f41-bf24-a90deeafc9db/chrome.css",
    "readme": "https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/03a8e7ef-cf00-4f41-bf24-a90deeafc9db/readme.md",
    "image": "https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/03a8e7ef-cf00-4f41-bf24-a90deeafc9db/image.png",
    "author": "Nimit1705",
    "version": "1.0.1",
    "tags": [],
    "createdAt": "2025-02-23",
    "updatedAt": "2025-02-23",
    "preferences": "https://raw.githubusercontent.com/zen-browser/theme-store/main/themes/03a8e7ef-cf00-4f41-bf24-a90deeafc9db/preferences.json",
    "enabled": true
  }
}
```

It gets rid of two mods but you should be able to add those back tonight, after a major release that will patch this.

**Comment by stantios** [comment]
Unfortunately, that didn't work and I still don't see the Sine section in preferences.

**Comment by Buckeyes23** [comment]
> Unfortunately, that didn't work and I still don't see the Sine section in preferences.

Try restarting from about:support clearing the startup cache a few times.. I did this and it kicked in

**Comment by CosmoCreeper** [comment]
@stantios try what @Buckeyes23 said and if that still doesn't work, open up ctrl+shift+j and then tell me what it says there.

**Comment by Buckeyes23** [comment]
> [@Buckeyes23](https://github.com/Buckeyes23) I believe the issue is due to a homepage failure, could you provide me with the same data I have requested for the original poster?

I actually got frustrated with it disappearing and wanted to see if it was my zen install, so I uninstalled on both computers and did a fresh install of zen. Still had the problem with the autoinstall though.. do you still want that json file?

**Comment by stantios** [comment]
> [@stantios](https://github.com/stantios) try what [@Buckeyes23](https://github.com/Buckeyes23) said and if that still doesn't work, open up ctrl+shift+j and then tell me what it says there.

Cleared it 10 times, that did not work. Here is the console:
![Image](https://github.com/user-attachments/assets/fbcc4435-f0f3-4872-b8d2-c4c5bfd028f8)

**Comment by CosmoCreeper** [comment]
@Buckeyes23 yes, it would be helpful. Also, what was happening with the auto-installer? Was it completely crashing?

@stantios It appears Sine is not even loading at all. Could you re-run the auto-installer for the latest version? Also, what are you inputting as the location of your Zen installation and are you picking the right profile?

**Comment by Buckeyes23** [comment]
> [@Buckeyes23](https://github.com/Buckeyes23) yes, it would be helpful. Also, what was happening with the auto-installer? Was it completely crashing?

[zen-themes.json](https://github.com/user-attachments/files/20427840/zen-themes.json)

Same problems we had last week, autoinstaller window flashes for a brief second and nothing gets installed

**Comment by stantios** [comment]
> [@stantios](https://github.com/stantios) It appears Sine is not even loading at all. Could you re-run the auto-installer for the latest version? Also, what are you inputting as the location of your Zen installation and are you picking the right profile?

I re-ran the installer but, that did not do much and the issue still exists. Here are outputs from when I ran the installer:
![Image](https://github.com/user-attachments/assets/3ccef772-c5b4-4333-a704-d62bde24744d)

**Comment by CosmoCreeper** [comment]
@stantios I believe the issue could be to one of the various things I have fixed in a new update for Sine's nightly build, Cosine. You should be able to replace the contents of the sine.uc.mjs file with the one from the Cosine branch on here, https://github.com/CosmoCreeper/Sine/blob/cosine/sine.uc.mjs. Once doing that, let me know what happens.

**Comment by stantios** [comment]
I replaced the ``sine.uc.mjs`` in chrome/JS to the one in the Cosine branch but for some reason, that did not work either and the issue still exists.

**Comment by stantios** [comment]
I don't think Sine is loading since there are no console messages that mention cosine has loaded. It might be a problem with the installer but at the same time, all the files are present so I don't think it is the installer.

**Comment by th1lo** [comment]
I've uninstalled and re-installed zen like 5 times and executed installer and its also not showing up for me. thought i'm just to dumb to install it and was going crazy over it.

![Image](https://github.com/user-attachments/assets/99ab5138-6c21-46ba-a29c-a301e8bbf46d)

EDIT: Enter the location of your Zen installation:
should this be application support or the app itself?

**Comment by CosmoCreeper** [comment]
@th1lo the application installation location should be the install directory, not about:support. You also have to clear your startup cache.

EDIT: also, ensure you installed in the right profile.

**Comment by CosmoCreeper** [comment]
@stantios make sure you are installing on the correct profile and that your installation directory is correct. Other than that, it should at least say it is loaded.

**Comment by stantios** [comment]
The installer identifies my profile directory and as you can see from the screenshot, I have selected the right path to my zen installation. For the zen installation path, should it be ``/Applications/Zen.app``? Or, is ``/Users/<username>/Library/Application Support/zen`` fine?

**Comment by drpencilcase** [comment]
I was having the same issue using it on macOS. Then I checked the Autoconfig instructions and found that you actually have to copy `config` and `configprefs` to the `Resources` folder as below.

Now it's working well. 


> Firefox is typically installed to /Applications/Firefox.app/Contents/MacOS/ or /Applications/Firefox Nightly.app/Contents/MacOS/
> 
> Copy defaults/ and config.js to /Applications/Firefox.app/Contents/Resources/ from the program folder. config.js should end up in the /Applications/Firefox.app/Contents/Resources/ directory.

**Comment by CosmoCreeper** [comment]
@drpencilcase thanks for finding that! It turns out the issue is the installation directory you have passed to the auto-installer. I dont have a mac but ill figure it out on monday. Until then, I suggest going with the solution above.

**Comment by stantios** [comment]
> I was having the same issue using it on macOS. Then I checked the Autoconfig instructions and found that you actually have to copy `config` and `configprefs` to the `Resources` folder as below.
> 
> Now it's working well.

Yep, that worked. I had to put the zen installation directory to ``/Applications/Zen.app/Contents/Resources`` for it to work. It would be nice if Cosine could automatically detect the installation directory and if it cannot find it, it would ask the user for the installation directory.

**Comment by CosmoCreeper** [comment]
@stantios yes, that is planned behavior for an upcoming release. Glad to hear its worked though!

**Comment by lockieluke** [comment]
it wiped my resources folder and lowkey broke my extensions

**Comment by CosmoCreeper** [comment]
@lockieluke ? That is not any sort of known or usual behavior. What platform? What did you put into the installation input?

**Comment by lockieluke** [comment]
> [@lockieluke](https://github.com/lockieluke) ? That is not any sort of known or usual behavior. What platform? What did you put into the installation input?

`/Applications/Zen.app/Contents/Resources` only defaults and config-prefs.js were left

**Comment by CosmoCreeper** [comment]
@lockieluke type in Zen Browser.app instead. There probably wasnt a Zen.app and it just added those files.
